config/routes.rb
Rails.application.routes.draw do
    devise_for :admins, controllers:{
        sessions: 'admins/sessions'  
}
    devise_for :users, controllers:{
        sessions: 'users/sessions'
}
    
  resources :juegos 
    
    
    devise_scope :admin do
        get "admins/users/list",
        to: "admins/sessions#list",
        as: "list"
    end
    root to: 'juegos#index'
end

app/models/juego.rb
class Juego < ApplicationRecord
    has_attached_file :image, style: { thumb: '120x120', large: '300x400' }, default_url: "/images/:style/missing.png"
    validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/controllers/juegos_controller.rb
class JuegosController < ApplicationController
  before_action :set_juego, only: [:show, :edit, :update, :destroy]

  # GET /juegos
  # GET /juegos.json
  def index
    @juegos = Juego.all
  end

  # GET /juegos/1
  # GET /juegos/1.json
  def show
  end

  # GET /juegos/new
  def new
    @juego = Juego.new
  end

  # GET /juegos/1/edit
  def edit
  end

  # POST /juegos
  # POST /juegos.json
  def create
    @juego = Juego.new(juego_params)

    respond_to do |format|
      if @juego.save
        format.html { redirect_to @juego, notice: 'El juego se a creado satisfactoriamente.' }
        format.json { render :show, status: :created, location: @juego }
      else
        format.html { render :new }
        format.json { render json: @juego.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /juegos/1
  # PATCH/PUT /juegos/1.json
  def update
    respond_to do |format|
      if @juego.update(juego_params)
        format.html { redirect_to @juego, notice: 'Juego actualizado exitosamente.' }
        format.json { render :show, status: :ok, location: @juego }
      else
        format.html { render :edit }
        format.json { render json: @juego.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /juegos/1
  # DELETE /juegos/1.json
  def destroy
    @juego.destroy
    respond_to do |format|
      format.html { redirect_to juegos_url, notice: 'Juego eliminado exitosamente.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_juego
      @juego = Juego.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def juego_params
      params.require(:juego).permit(:nombre, :descripcion, :desarrollador, :plataforma, :modojuego, :image)
    end
end

app/helpers/juegos_helper.rb
module JuegosHelper
end

app/views/juegos/_form.html.erb
<%= form_with(model: juego, local: true) do |form| %>
  <% if juego.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(juego.errors.count, "error") %> prohibited this juego from being saved:</h2>

      <ul>
      <% juego.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
<% end %>
<div class="pd">
<form>
 <div class="col-md-12 col-sm-12 col-xs-12 padd" role="form" id="form">
 <h1><legend>Formulario de registro/edición</legend></h1>
  <div class="form-group">
    <%= form.label :nombre, class: "control-label col-md-2" %>
    <%= form.text_field :nombre, id: :juego_nombre, class:"form-control"%>
  </div>

  <div class="form-group">
    <%= form.label :descripcion, class: "control-label col-md-2" %>
    <%= form.text_area :descripcion, id: :juego_descripcion, class:"form-control", :rows => 6 %>
  </div>

  <div class="form-group">
    <%= form.label :desarrollador, class: "control-label col-md-2" %>
    <%= form.text_field :desarrollador, id: :juego_desarrollador, class:"form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :plataforma, class: "control-label col-md-2" %>
    <%= form.select :plataforma, options_for_select([
    ["Seleccione una opción", ""],
    ["XBOX ONE", "XBOX ONE"],
    ["WII U", "WII U"],
    ["PLAY STATION 4", "PLAY STATION 4"],
    ["PC", "PC"]
    ]), {}, {:class => "form-control"} %>
  </div>

  <div class="form-group">
    <%= form.label :modojuego, class: "control-label col-md-2" %>
    <%= form.select :modojuego, options_for_select([
    ["Seleccione una opción", ""],
    ["ACCIÓN", "ACCIÓN"],
    ["RPG", "RPG"],
    ["SHOOTER", "SHOOTER"],
    ["DEPORTES", "DEPORTES"]
    ]), {}, {:class => "form-control"} %>
  </div>

  <div class="form-group">
    <%= form.label :imagen, class: "control-label col-md-2" %>
    <%= form.file_field :image, id: :juego_image, class:"form-control" %>
  </div>

  <div class="actions">
    <%= form.submit class:"btn btn-primary btn-lg center-block" %>
  </div>  
  <div class="actions">
      <center><%= link_to 'Mostrar', @juego, class: "btn btn-warning" %>
      <%= link_to 'Rregresar', juegos_path, class: "btn btn-info" %></center>
</div>
    </div>
</form>
</div>
<% end %>

app/views/juegos/edit.html.erb
<%= render 'form', juego: @juego %>

 |s

app/views/juegos/index.html.erb
<div class="table-responsive m">
<table class="table table-hover table-bordered">
  <thead>
    <tr class="warning">
      <th>Nombre</th>
      <th>Descripción</th>
      <th>Desarrollador</th>
      <th>Plataforma</th>
      <th>Modo de juego</th>
      <th>Imagen</th>
      <th colspan="3">Edición</th>
    </tr>
  </thead>
  <tbody>
    <% @juegos.each do |juego| %>
      <tr class='success'>
        <td><%= juego.nombre %></td>
        <td><%= juego.descripcion %></td>
        <td><%= juego.desarrollador %></td>
        <td><%= juego.plataforma %></td>
        <td><%= juego.modojuego %></td>
        <td><%= image_tag(juego.image.url, class:"ava") %></td>
        <td><%= link_to 'Mostrar', juego, class:"btn btn-success" %></td>
        <td><%= link_to 'Editar', edit_juego_path(juego), class:"btn btn-info" %></td>
        <td><%= link_to 'Eliminar', juego, method: :delete, data: { confirm: '¿Estas seguro de eliminar el registro?' }, class:"btn btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<br>
<center>
<%= link_to 'Nuevo Juego', new_juego_path, class:"btn btn-warning btn-lg" %>
</center>

app/views/juegos/new.html.erb
<%= render 'form', juego: @juego %>

app/views/juegos/show.html.erb
<div class="pd">
<form>
 <div class="col-md-12 col-sm-12 col-xs-12 padd" role="form" id="form">
 <h1><legend>Juego Perrote</legend></h1>
  <div class="form-group">
      <label class="control-label"><strong>Nombre del juego:</strong></label>
      <%= @juego.nombre %>
  </div>
  <div class="form-group">
      <label class="control-label"><strong>Descripción:</strong></label>
      <%= @juego.descripcion %>
  </div>
  <div class="form-group">
      <label class="control-label"><strong>Desarrollador:</strong></label>
      <%= @juego.desarrollador %>
  </div>
  <div class="form-group">
      <label class="control-label"><strong>PLataforma:</strong></label>
      <%= @juego.plataforma %>
  </div>
  <div class="form-group">
      <label class="control-label"><strong>Modo de Juego:</strong></label>
      <%= @juego.modojuego %>
  </div>
  <div class="form-group">
      <label class="control-label"><strong>Imagen:</strong></label>
      <center><%= image_tag(@juego.image.url, class: "thumbnail img-responsive") %></center>
  </div>
  <center>
<%= link_to 'Editar', edit_juego_path(@juego), class: "btn btn-warning btn-lg" %> |
<%= link_to 'Regresar', juegos_path, class: "btn btn-info btn-lg" %>
</center>
</div>
</form>
</div>