config/routes.rb
Rails.application.routes.draw do
    devise_for :admins, controllers:{
        sessions: 'admins/sessions'  
}
    devise_for :users, controllers:{
        sessions: 'users/sessions'
}
    
  resources :juegos 
    
    
    devise_scope :admin do
        get "admins/users/list",
        to: "admins/sessions#list",
        as: "list"
    end
    root to: 'juegos#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <title>Juegos Chidoris</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>
<body>

<nav class="navbar navbar-inverse" role="navigation">
    <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse"> 
    <span class="sr-only"></span> 
    <span class="icon-bar"></span> 
    <span class="icon-bar"></span> 
    <span class="icon-bar"></span> 
    </button> 
    <a class="navbar-brand" href="#">Juegos Perrones</a> </div>
    <div class="collapse navbar-collapse navbar-ex1-collapse">
    <ul class="nav navbar-nav">
      <li class="active"><a href="#">Inicio</a></li>
      <li><a href=#>Juegos</a></li>
      <li><a href="<%= juegos_path %>">Registrar Juegos</a></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <% if user_signed_in? %> 
               <br>
                <font color="white">Bienvenid@ <strong><%= current_user.email %></strong></font>
                <%= link_to 'Editar Perfil', edit_user_registration_path, class: "btn btn-link" %> | 
                <%= link_to "Cerrar Sesión", destroy_user_session_path, method: :delete, class: "btn btn-link" %>             
                <% elsif admin_signed_in? %> 
                <br>
                <font color="white">Bienvenid@ <strong><%= current_admin.email %></strong></font>
                <%= link_to 'Editar Perfil', edit_user_registration_path, :class => 'navbar-link' %> | 
                <%= link_to "Cerrar Sessión", destroy_user_session_path, method: :delete, :class => 'navbar-link' %> 
                <% else %> 
                <br>
                <%= link_to "Registarse", new_user_registration_path, class: "btn btn-link" %> | 
                <%= link_to "Iniciar Sesión", new_user_session_path, class: "btn btn-link" %> 
                <% end %>
    </ul>
    </div>
</nav>
   <% if notice %> 
	        <p class="alert alert-success"><%= notice %></p> <% end %> 
        <% if alert %> 
	        <p class="alert alert-danger"><%= alert %></p> 
    <% end %>
<%= yield %>
</body>
</html>